/// Modifiers that are manually excluded from the modifier generator.
let denylist = [
    "modifier",
    "equatable",
    
    "accessibilityCustomContent",
    
    "environment",
    "environmentObject",
    "transformEnvironment",
    "preference",
    "onPreferenceChange",
    "transformPreference",
    "anchorPreference",
    "transformAnchorPreference",
    "onChange",
    "onReceive",

    "alignmentGuide",
    "layoutValue",

    "focusedObject",
    "focusedSceneObject",
    "focusedSceneValue",
    "focusedValue",
    
    "navigationDocument",
    
    "previewContext",
    "previewDevice",
    "previewInterfaceOrientation",
    "previewLayout",
    
    "onCommand",
    
    "tag",
    "id",
    
    "task",
    
    "fileDialogURLEnabled",
    
    "containerValue",
    
    "textRenderer",
    
    "tabViewCustomization",
    
    "menuButtonStyle",
    
    "navigationViewStyle",
    
    "disclosureGroupStyle",
    
    "automationElement",

    // manually implemented due to argument order edge cases
    "searchScopes",
    "searchCompletion",
    "onSubmit",
    "mask",
    "matchedGeometryEffect",
    "rotation3DEffect",
    "perspectiveRotationEffect",
    "presentationDetents",
    "focusScope",
    "prefersDefaultFocus",
    "navigationTransition",
    "matchedTransitionSource",
    
    // manually implemented for `Text`
    "font",
    "fontWeight",
    "fontDesign",
    "fontWidth",
    "foregroundStyle",
    "bold",
    "italic",
    "strikethrough",
    "underline",
    "monospaced",
    "monospacedDigit",
    "kerning",
    "tracking",
    "baselineOffset",
    "textScale",
    
    // fixme: missing types
    "accessibilityRotor",
    "accessibilityChartDescriptor",
    "accessibilityFocused",
    "accessibilityQuickAction",
    "copyable",
    "cuttable",
    "defaultFocus",
    "digitalCrownRotation",
    "exportableToServices",
    "exportsItemProviders",
    "fileExporter",
    "fileImporter",
    "fileMover",
    "focused",
    "importableFromServices",
    "importsItemProviders",
    "itemProvider",
    "onContinuousHover",
    "onContinueUserActivity",
    "onCopyCommand",
    "onDrag",
    "onDrop",
    "onOpenURL",
    "onPasteCommand",
    "pageCommand",
    "pasteDestination",
    "sensoryFeedback",
    "transaction",
    "userActivity",
    "allowedDynamicRange",
    "alternatingRowBackgrounds",
    "buttonRepeatBehavior",
    "colorEffect",
    "containerBackground",
    "dialogSeverity",
    "distortionEffect",
    "fileDialogBrowserOptions",
    "layerEffect",
    "layoutDirectionBehavior",
    "menuActionDismissBehavior",
    "paletteSelectionEffect",
    "springLoadingBehavior",
    "touchBar",
    "touchBarItemPresence",
    "typesettingLanguage",
    "fileDialogMessage",
    "typeSelectEquivalent",
    "fileExporterFilenameLabel",
    "dialogIcon",
    "fileDialogDefaultDirectory",
    "onCutCommand",
    "accessibilityElementModifier",
    "tableColumnHeaders",
    "defaultAppStorage",
    "accessibilityRotorEntry",
    "accessibilityLinkedGroup",
    "handlesExternalEvents",
    "accessibilityLabeledPair",
    "fileDialogConfirmationLabel",
    "onCopyCommand",
    "accessibilityElement",
    "presentedWindowStyle",
    "presentedWindowToolbarStyle",
    "onScrollTargetVisibilityChange",
    "matchedTransitionSource",
    "scrollInputBehavior",
]
