name: ${LVN_APP_NAME}
include:
  - path: base_spec.yml
    relativePaths: false
  - path: "project_watchos.yml"
    relativePaths: false
targets:
  ${LVN_APP_NAME}:
    type: application
    supportedDestinations:
      - iOS
      - macOS
      - tvOS
    sources:
      - ${LVN_APP_NAME}
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: ${LVN_BUNDLE_IDENTIFIER}
    dependencies:
      - package: LiveViewNative